// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBFilOB-FlQEAnG8R3zdKK9A76_MI9wp8',
    appId: '1:304363613786:web:c1d93aa6525f760050f263',
    messagingSenderId: '304363613786',
    projectId: 'duitwise-dc914',
    authDomain: 'duitwise-dc914.firebaseapp.com',
    storageBucket: 'duitwise-dc914.firebasestorage.app',
    measurementId: 'G-FLF95BZ5M8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDInjWcRoImBWB1q0xds-FysOdTn-557-Q',
    appId: '1:304363613786:android:dd5c19be56bea43350f263',
    messagingSenderId: '304363613786',
    projectId: 'duitwise-dc914',
    storageBucket: 'duitwise-dc914.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXhoQFL710Z_9xLhi4a-nU6X757lA4syE',
    appId: '1:304363613786:ios:fe84e447cee26fa350f263',
    messagingSenderId: '304363613786',
    projectId: 'duitwise-dc914',
    storageBucket: 'duitwise-dc914.firebasestorage.app',
    iosBundleId: 'com.example.duitwiseApp',
  );
}
